[package]
name = "config-builder"
version.workspace = true
edition.workspace = true

[dependencies]
gpui.workspace = true
gpui-component.workspace = true
regex = "1.13.1"
serde_yaml = "0.9"
settings = { path = "../settings" }
ui = { path = "../ui" }
workbench-integration = { path = "../workbench-integration" }
