[package]
name = "workbench-integration"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
schemars.workspace = true
serde_json.workspace = true
which = "7.0"
workbench-preprocessor = { git = "https://github.com/south-asian-canadian-digital-archive/workbench-preprocessor" }
serde_yaml = "0.9"
indexmap = "2.0"
