host: https://isle.dvnl.work
credentials_file_path: C:\Users\Arnav\Projects\islandora_workbench\credentials_isle.yml
input_csv: metadata.csv
task: create
fixity_algorithm: md5
adaptive_pause: 3
allow_missing_files: true
remind_user_to_run_check: true
log_file_path: ./g/logs/workbench.log
timestamp_rollback: true
rollback_file_include_node_info: true
rollback_config_file_path: ./g/rollback/config/rollback.yml
rollback_dir: ./g/rollback/csv
rollback_config_filename_template: rollback_${config_filename}.yml
shutdown:
- uv run python ./g/scripts/post_action_commit.py
allow_adding_terms: true
protected_vocabularies:
- islandora_models
- islandora_display
- islandora_media_use
- issuance_modes
- resource_types
- physical_form
- genre
- copyright
- terms_of_use
- concerns_corrections
id_field: accessIdentifier
ignore_csv_columns:
- machineName
- id_field
- file_extension
- fileTitle
csv_value_templates:
- field_linked_agent: relators:cre:person:$csv_value
- field_subjects_name: person:$csv_value
- field_subject_name__organization: corporate_body:$csv_value
- field_sacda_thesaurus: subject:$csv_value
- file: access/$csv_value
csv_field_templates:
- field_model: Image
query_csv_id_to_node_id_map_for_parents: true
